# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Jono
tagline:          'like a druid, but a <br>little more modern'
description:      'Jono Shields is a web developer, game programmer, coffee addict...'
url:              https://jono.tech
baseurl:          ''

twitter:
    username: foocodes

author:
  name:           'Jono Shields'
  twitter:        foocodes    

logo : /public/icon.png


  
collections:
    - projects
  
gems: [ 'jekyll-seo-tag', 'jekyll-sitemap']
